# Generated by Django 2.2.11 on 2020-03-17 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_post_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
    ]
