# Generated by Django 2.2.11 on 2020-03-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_id', models.IntegerField(db_index=True)),
                ('blogger_id', models.IntegerField(db_index=True)),
            ],
        ),
    ]
