# Generated by Django 2.2.11 on 2020-03-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader_id', models.IntegerField(db_index=True)),
                ('post_id', models.IntegerField(db_index=True)),
                ('author_id', models.IntegerField(db_index=True)),
            ],
        ),
    ]
